// app/layout.js
import { Roboto_Condensed } from "next/font/google";
import './globals.css';
import I18nextProvider from '@/Total/I18nextProvider';
import TranslationReady from '@/Total/TranslationReady';

import {
   Header,
   Footer
} from '../Components';

const robotoCondensed = Roboto_Condensed({
   subsets: ['latin'],
   variable: '--font-roboto-condensed',
   display: 'swap',
});

export const metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {

   return (
      <html lang="en">
         <body
            className={`${robotoCondensed.variable} App`}
            style={{ position: 'relative', zIndex: 0 }}
         >
            <I18nextProvider>
               <TranslationReady>{/* индикатор загрузки, пока переводы не загрузятся */}
                  <div className="wrapper">
                     <Header />
                     <div className={`ContantContainer`}>
                        {children}
                     </div>
                     <Footer />
                  </div>
               </TranslationReady>
            </I18nextProvider>
         </body>
      </html>
   );
}